### ISSUE TITLE
Env Vars

### ISSUE THREAD

**Issue by bluetidepro** [DennisAlund/firebase-slack-app#1]
I see in the Travis.yml there is a few vars like `$SLACK_SECRET`, `$SLACK_ID`, `$FIREBASE_DEPLOY_KEY`, etc. Where are those coming from? I don't see a file in the repo that has those vars? Is it like an `.env` file that has those, that isn't in github? An example would be great to see how the travis deploy gets those vars. Thanks!

**Comment by bluetidepro** [comment]
Same with the functions index where there is like `process.env.GCLOUD_PROJECT`? Where is all that stuff set?

**Comment by bluetidepro** [comment]
@DennisAlund Any idea on this? :)

**Comment by DennisAlund** [comment]
Sorry for the delay in reply, I've been on the road. The env variables comes from your Slack App project settings: https://api.slack.com/apps

![slack-ids](https://user-images.githubusercontent.com/2051607/27590978-a90bcc9e-5b50-11e7-9d55-bc8ad7a21153.png)

You will have to set those variables as CI env variables:https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

The `process.env.GCLOUD_PROJECT` is a node environment variable that will be set to your project's id. See: https://cloud.google.com/appengine/docs/flexible/nodejs/runtime#environment_variables
